---
- name: "tmconfpy example playbook"
  hosts: all
  connection: httpapi
  gather_facts: false

  vars:
    provider:
      server: 192.0.2.245
      server_port: 443
      user: admin
      password: admin  # use vault!
      validate_certs: yes
    # map provider variables to collection v2 variables
    ansible_host: "{{ provider.server }}"
    ansible_user: "{{ provider.user }}"
    ansible_httpapi_password: "{{ provider.password }}"
    ansible_httpapi_port: "{{ provider.server_port }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: "{{ provider.validate_certs }}"


  tasks:
    - name: "Fetch bigip_user.conf tabular"
      simonkowallik.tmconfpy.tmconf_get:
        configfile: /config/bigip_user.conf
        format: tabular
      register: tabular_config

    - name: "Print bigip_user.conf tabular"
      ansible.builtin.debug:
        var: tabular_config.tmconf_tabular

    - name: "Fetch bigip_user.conf"
      simonkowallik.tmconfpy.tmconf_get:
        configfile: /config/bigip_user.conf
      register: config

    - name: "Print bigip_user.conf"
      ansible.builtin.debug:
        var: config.tmconf
